---
title: "Building a Project"
date: 2019-07-28T10:44:45-07:00
draft: false
weight: 30
---

== Building a Project

Socrates can compile a asciidoc manuscript into single HTML and PDF files.

=== Checking a Project

Socrates performs a check for any missing files referenced by _include_ directives in _master.adoc_ as well as a check for the _references.bib_ file. This check is run before every build. But it can also be run independently by using the _check_ command.

[source,console]
----
socrates check
----

The _check_ command will report any missing files.

=== Building an HTML File

Socrates is configured to produce a single HTML file from your asciidoc source files. This includes compiling any images by using the https://asciidoctor.org/docs/user-manual/#managing-images[_data-uri_] attribute. To build an HTML file, enter:

[source,console]
----
socrates html
----

This will produce a self-contained HTML file in the _build_ folder of your project.

=== Building a PDF File with https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor-pdf]

Socrates _pdf_ uses the default style (in the _resources/pdfstyles_ folder) to create a PDF file from the asciidoc source files. To build a PDF, enter:

[source,console]
----
socrates pdf
----

This will create a PDF in the _build_ folder.

The default style can be edited to change the layout, fonts, etc. of the PDF produced. More more information on configuring the styles, see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoctor-pdf Theming Guide]

=== Building a PDF File with https://github.com/asciidoctor/asciidoctor-fopub[Asciidoctor-fopub]

Socrates _fopub_ uses the Asciidoctor-fopub docbook tool-chain to create a PDF file from the asciidoc source files. To build a PDF, enter:

[source,console]
----
socrates fopub
----

This will create a PDF in the _build_ folder.

See the link:../../getting-started/prereqs[Prerequisites] page for details on installing Asciidoctor-fopub.

=== Building a DocBook 5 XML File

Socrates _docbook_ command creates a DocBook 5 file from the asciidoc source files. To build a Docbook file, enter:

[source,console]
----
socrates docbook
----

This will create a PDF in the _build_ folder.
