---
title: "Building a Project"
date: 2019-07-28T10:44:45-07:00
draft: false
weight: 30
---

== Building a Project

Socrates can compile an asciidoc manuscript into an HTML, DocBook, or PDF file. Whether building a PDF, DocBook, or HTML file, the build proceeds int two steps:

. Validation
. Compilation

=== Validating with the _check_ Command

Socrates recursively performs a check for any missing files referenced by attributes, include directives, and block macros (and inline images). This check is run before every build. But it can also be run independently by using the _check_ command.

The _check_ command will display a tree of a project's Socrates file references (include, block macros, certain document attributes) noting any missing files (and the line number in the file containing the broken file reference).

[source,console]
----
socrates check
----

The _check_ command will report any missing files. The _check_ command recursively scans for all included files in the project. If validation passes, compilation begins using the external tools we installed earlier.

{{% notice tip %}} 
By default, Socrates will not build a manuscript when validation has failed. You can skip the Socrates validation step by including the "--skip" flag when entering the _build html_ command (or any of the build commands).
{{% /notice %}}


=== Building an HTML File

==== Building

Socrates is configured to produce a single self-contained (including images) HTML file from your asciidoc source files. To build an HTML file, enter:

[source,console]
----
socrates html
----

This will produce a self-contained HTML file in the _build/html_ folder of your project.

==== Styling

Thanks to the Asciidoctor community, there are a variety of CSS stylesheets to choose from to style the HTML output. Many thanks go to the following for producing these themes:

* https://github.com/asciidoctor/asciidoctor-stylesheet-factory[]
* https://github.com/darshandsoni/asciidoctor-skins[]
* https://github.com/nerk/asciidoctor-bs-themes[]
* https://github.com/Mogztter/asciidoctor-stylesheets[]

For convenience, the CSS files from these projects have been collected in the _resources/htmlstyles_ folder. (These will be kept up to date with each new release of Socrates.)

By default, Socrates uses the _asciidoctor.css_ file from the official Asciidoctor Stylesheet Factory project. To change the CSS applied, change the _:stylesheet:_ attribute in _master.adoc_. Enter the path to the CSS file you wish to have applied (or you can create your own):

[source,asciidoc]
----
:stylesheet: resources/htmlstyles/stylesheets-bulma/darkly.css
----


=== Building a PDF File with https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor-pdf]

Socrates _pdf_ uses the default style (in the _resources/pdfstyles_ folder) to create a PDF file from the asciidoc source files. To build a PDF, enter:

[source,console]
----
socrates pdf
----

This will create a PDF in the _build/pdf_ folder.

The default style can be edited to change the layout, fonts, etc. of the PDF produced. More more information on configuring the styles, see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoctor-pdf Theming Guide]

=== Building a PDF File with https://github.com/asciidoctor/asciidoctor-fopub[Asciidoctor-fopub]

Socrates _fopub_ uses the Asciidoctor-fopub docbook tool-chain to create a PDF file from the asciidoc source files. To build a PDF, enter:

[source,console]
----
socrates fopub
----

This will create a PDF in the _build_ folder.

See the link:../../getting-started/prereqs[Prerequisites] page for details on installing Asciidoctor-fopub.

=== Building a DocBook 5 XML File

Socrates _docbook_ command creates a DocBook 5 file from the asciidoc source files. To build a DocBook file, enter:

[source,console]
----
socrates docbook
----

This will create a DocBook 5 XML file in the _build/docbook_ folder.
