---
title: "Creating a Project"
date: 2019-07-28T10:44:45-07:00
draft: false
weight: 10
---

Socrates performs three related functions:

. Creating asciidoc manuscripts.
. Validating asciidoc manuscripts.
. Building asciidoc manuscripts.

Let's start with creating asciidoc manuscripts.

== Creating a Socrates Project

Create a new folder with a short name for your manuscript, e.g., _hume-causation_. This name will be used for the file name of the compiled manuscript files (PDF or HTML).

From within the new folder, _hume-causation_ in our example, initialize a Socrates project:

[source,console]
----
socrates init
----

The init command creates the folder structure and preliminary files for a manuscript.

{{% notice tip %}}
To see verbose output for _init_ and any Socrates command, use the -v or --verbose switch.
{{% /notice %}}

=== Folders

Within the folder created above (_hume-causation_), the following folders are created:

*assets/*: to hold any files not used to compile your manuscript that you may wish to keep associated with the manuscript(e.g., PDFs of papers cited, notes, etc.).

*back_matter/*: to hold elements of a manuscript that follow the main text (e.g., appendix, bibliography, colophon, glossary, and index).

*front_matter/*: to hold elements of a manuscript prior to the main text (e.g., abstract, dedication, preface)
 
*images/*: to hold images used in the manuscript
 
*parts/*: to hold manuscript files for parts and chapters.

*resources/*: to hold PDF and HTML styles used to generate manuscript

=== Files

The init command also created several files:

*/ (project root)*: 

** _master.adoc_ (contains manuscript _attributes_ statements and _include_ directives)
** _references.bib_ (which contains or will contain bibtex compliant references)
** _socrates.toml_ (contains Socrates configuration options)

*back_matter/*: 

** _bibliography.adoc_
** _colophon.adoc_
** _glossary.adoc_
** _index.adoc_
** _01_appendix.adoc_

*front_matter/*: 

** _abstract.adoc_
** _dedication.adoc_
** _preface.adoc_

*_parts/part_01_/:*

** _part_01.adoc_

*_parts/part_01/chapters/chapter_01/_:*

** _chapter_01.adoc_
** _include_01.adoc_
** _include_02.adoc_

as well as numerous styles in the _resources_ folder.

{{% notice note %}}
By default, if Git is installed, a git repository will be created for a new project. To skip initializing a Git repository for a project, pass the --nogit (or -n) flag to the init command.
{{% /notice %}}

{{% notice note %}}
If you want a bare project (a basic master.adoc with no _include_ directives) and none of the default folders and files, use the --bare (or -b) flag with the _init_ command..
{{% /notice %}}

{{% notice tip %}}
_appendix_01.adoc_, you'll have noticed, is named with a two digit number. Like parts and chapters, a manuscript can have multiple appendixes. Since there may be more than one appendix, naming them with a numerical suffix makes the files appear in the same order in file browsers as they appear in your _master.adoc_. 
{{% /notice %}}

== Manuscript Configuration

Manuscripts are configured in the _master.adoc_ file in the project root folder.

=== Attributes

Attributes are listed at the top of the _master.adoc_ file. Some are self-explanatory, others less so. See https://asciidoctor.org/docs/user-manual/#attributes[attributes] section of the Asciidoctor manual for more information.

=== _include_ Directives

One of the benefits of using Asciidoctor is its very useful _include_ directive. This allows an asciidoc manuscript to be broken into several files, disassembled one might say, that are then reassembled when the manuscript is compiled. Here is a snippet from _master.adoc_ that illustrates how the _include_ directive is used to perform this reassembly:

[source,console]
....
 include::front_matter/dedication.adoc[]
 include::front_matter/preface.adoc[]
 include::parts/01_part/01_part.adoc[]
 include::parts/01_part/01_chapter.adoc[leveloffset=+1]
 include::back_matter/01_appendix.adoc[]
 include::back_matter/glossary.adoc[]
 include::back_matter/bibliography.adoc[]

 ifdef::backend-pdf[]
 include::back_matter/index.adoc[]
 endif::[]

 ifdef::backend-docbook5[]
 include::back_matter/index.adoc[]
 endif::[]

 include::back_matter/colophon.adoc[]
....

At compile time, Asciidoctor places the content of the file referenced by the _include_ directive into the master document at the location of the directive. Learn more about the _include_ directive at the https://asciidoctor.org/docs/user-manual/#include-partitioning[Asciidoctor Manual] page.

{{% notice note %}} 
Notice that the _include_ directives for the index are enclosed in an if...then block. HTML does not support indexing, so an index will only be produced when compiling a PDF or a Docbook file.
{{% /notice %}}

=== Manuscripts with Parts (default)

The _include_ directives reassemble the manuscript in the order of appearance in _master.adoc_. The above set of _include_ directives is for a manuscript with multiple parts, each with a set of chapters. This is the default setup created with the _init_ command.

=== Manuscripts without Parts 

Not all manuscripts need parts. In that case, simply remove the _include_ directive for the part_01.adoc_ file. Also, remove the _leveloffset_ for chapters (see the https://asciidoctor.org/docs/user-manual/#include-partitioning[Asciidoctor Manual] for more on _include_ directives and the _leveloffset_ setting). To get of the unneeded _part_01_ folder, move the _chapter_01.adoc_ file into the _parts_ folder. Then delete _part_01_ folder and _part_01.adoc_ file from the project. 

The last step is to simplify the _include_ directives in _master.adoc_ as follows:

[source,console]
....
 include::front_matter/dedication.adoc[]
 include::front_matter/preface.adoc[]
 include::parts/chapter_01.adoc[]
 include::back_matter/appendix_01.adoc[]
 include::back_matter/glossary.adoc[]
 include::back_matter/bibliography.adoc[]

 ifdef::backend-pdf[]
 include::back_matter/index.adoc[]
 endif::[]

 ifdef::backend-docbook5[]
 include::back_matter/index.adoc[]
 endif::[]

 include::back_matter/colophon.adoc[]
....

=== Organize as You Wish

There is no reason why you need to use the folder and file structure of the _init_ project. It is a mere suggested structure. 

The only requirement for Socrates to validate and build asciidoc manuscripts (whether a single file or multiple nested files linked together by numerous include statements) is for the entry asciidoc file to be called _master.adoc_.

If you do not care for the default folder and file structure, delete everything but _master.adoc_ and remove all the _include_ directives in _master.adoc_. Or just init your project with the --bare flag.




