---
title: "Additional Tools"
date: 2019-07-28T10:44:45-07:00
draft: false
weight: 40
---

= Additional Tools

== Zotero Integration

Socrates supports references and bibliography generation using https://github.com/riboseinc/asciidoctor-bibliography[Asciidoctor-bibliography]. For complete instructions on using asciidoctor-bibliography, see the its github page. https://github.com/riboseinc/asciidoctor-bibliography[Asciidoctor-bibliography] relies on a bibtex file (src/references.bib) to populate manuscript references and a bibliography. Many programs can generate bibtex files.

https://www.zotero.org[Zotero], an open source reference manager, has excellent support for bibtex files when the https://github.com/retorquere/zotero-better-bibtex[BetterBibTex] add-on is enabled. One can then use Zotero to generate and update the references.bib files. Also, when using the https://github.com/retorquere/zotero-better-bibtex[BetterBibTex] add-on, the exported references.bib is updated every time a reference is added, edited, or deleted from the Zotero database.

== Visual Studio Code

Any text editor can be used to edit manuscript files. I recommend https://code.visualstudio.com[Visual Studio Code] because it has very good support for asciidoc files. VS Code with the https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[asciidoc extension] provides live preview, syntax highlighting, and more.

Also, if you choose to use VS Code, there is a very useful https://marketplace.visualstudio.com/items?itemName=mblode.zotero[Zotero connector] that allows placing citations directly in the editor right from VS Code. Also check out the following extensions:

* https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview[Mermaid Preview extension].
* https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml[BetterTOML]
* https://marketplace.visualstudio.com/items?itemName=phr0s.bib[Bibtext Language support]
* https://marketplace.visualstudio.com/items?itemName=SatakeRyota.asciidoc-icon-snippets[asciidoc icon snippets]
* https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool-en[English language support for LanguageTool]
* https://marketplace.visualstudio.com/items?itemName=wushuaiBUAA.autocomplete-english-word[English Word Hint]
* https://marketplace.visualstudio.com/items?itemName=joaompinto.vscode-graphviz[Graphviz Language support and Preview]
* https://marketplace.visualstudio.com/items?itemName=ban.spellright[Spellright]
* https://marketplace.visualstudio.com/items?itemName=jock.svg[SVG language support]
* https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer[SVG preview]


