---
title: "Socrates"
date: 2019-07-27T20:56:27-07:00
draft: false
---

== SOCRATES (v0.7.0)

=== Easing the use of Asciidoctor to produce manuscripts.

Socrates is a front-end CLI written in Go for creating and compiling manuscripts from asciidoc files. It uses the http://asciidoctor.org[Asciidoctor] tool-chain to create manuscript from a set of files. Socrates is written in Go so it produces a single executable file with no dependencies, making it easy to install and update.

Asciidoc is a well-designed language for producing rich and complicated manuscripts. Socrates eases the use of Asciidoc by providing a front-end to the Asciidoctor compiler that eases and speeds up development of a manuscript. Socrates assists in setting up a manuscript project, adding new items, and compiling those files into a final manuscript in PDF or HTML format.

Best of all, every file needed to construct a manuscript is entirely text, which means it can be easily version-controlled in Git!

This site includes instructions on how to install and use Socrates. There are also a number of Guides in the works:

* A guide to using Git to manage a manuscript project.
* A guide to using Asciidoctor-Bibliography to insert citations and bibliographies.
* A guide to using Asciidoctor-Diagram to generate diagrams and charts.
* A guide to using Rouge to provide source highlighting.
* A guide to using Zotero to manage the _references.bib_ file.
* A guide to using VS Code to manage and edit a manuscript.
* A guide to creating new HTML themes.
* A guide to creating a new PDF theme.

