---
title: "Understanding the Tools Behind Socrates"
date: 2019-07-28T10:44:45-07:00
draft: true
weight: 20
---

= Understanding the Tools Behind Socrates

Socrates generates HTML and PDF documents from a related set of files. These file contain only plain text. That is why they are easy to version control in Git. These files contain text written using several _markup languages_. In simple terms, a markup language is a way of _marking up_ ordinary text so that an specially programmed _interpetter_ can understand what to do with the text when it is rendered. HTML, for instance, is a markup language. 

== Markup Languages

Socrates of course relies on the Asciidoc markup language. Socrates also relies on these other markup languages:

* BIBTEX (a markup language used to store references in the _references.bib_ file).
* YAML (a markup language used in the _default-style.yml_ file in _resources/pdfstyles_).
* TOML (used for _socrates.toml_ configuration file)
* All of the markup languages used to create diagrams that are supported by Asciidoctor-diagram (e.g., mermaid, plantuml, and so on).

== Build Tools

Asciidoctor (and Asciidoctor-pdf) are compilers that produce HTML (and PDF) files from asciidoc files. Socrates was designed to serve as a front-end to these build tools.

== Filters

Socrates also relies on two tools that are used during the compile phase to change or add elements to a manuscript at build time.

Asciidoctor-bibliography is used to generate in text citations and generate a bibliography page in the back matter. 

If you work involve sharing code of any sort, Socrates supports source highlighting through Rouge. Properly marked up blocks will be passed through a filter to apply a color theme to the source code being displayed.

There are a wide number of diagram markup languages supported through Asciidoctor-diagram. 

This is meant to be a short introduction to the tools. Guides on using many of them follow.

== Git

Why the emphasis on all these plain text files? Because plain text file are easily version controlled. Using Git (or your preferred RCS), you can track every file and every line of every file for changes over time. It is time to bring the fantastic version control tools in the programming world to the world of writing. See the Guide on Git.

Most people likely use Microsoft Word or LibreOffice Write to author manuscripts. But these programs, though they provide a lovely GUI, are ultimately ill-suited to the task of writing a manuscript from beginning to end. Writing a lengthy manuscript is a long process of writing, editing, deleting, adding, more deleting and so on. In other words, a manuscript has a lifespan from opening a new file to the final manuscript. It is a process of fits and starts. And restarts. In other words, it is a series of revisions. What Socrates aims to help with is the task of recording, storing, and versioning those revisions.

Coders write text too. And, just like a manuscript, the software development process is a series of revisions. Keeping a record of those revisions is crucial to understanding how the code developed over iterations as well as allowing reverting back to older code if needed.

Of course MS Word has Document Tracking to allow some rudimentary revision control. But it is a poor substitute for the control and functionality of a proper revision control system like Git. But Git works best with plain text files. Hence Socrates.

